export const ALL_PROFESSIONS = [
  "Médico",
  "Enfermero",
  "Diseñador Gráfico",
  "Chef",
  "Fotógrafo",
  "Arquitecto",
  "Maestro de Primaria",
  "Veterinario",
  "Contador",
  "Piloto",
  "Abogado",
  "Periodista",
  "Marketing Digital",
  "Psicólogo",
  "Product Manager",
  "Ingeniero Civil",
  "Ingeniero Mecánico",
  "Ingeniero Químico",
  "Ingeniero Electricista",
  "Productor de Música",
  "Productor de Cine",
  "Productor de Televisión",
  "Científico",
  "Analista de Datos",
  "Carpintero",
  "Astronauta",
  "Bibliotecario",
  "Astrónomo",
  "Biólogo",
  "Especialista en Ciberseguridad",
  "Emprendedor",
  "Especialista en Ventas",
  "Investigador de Laboratorio",
  "Investigador de Mercado",
  "Investigador de Datos"
];
