export const ALL_PROFESSIONS = [
  "Médico general",
  "Enfermero",
  "Ingeniero de software",
  "Diseñador gráfico",
  "Chef",
  "Fotógrafo",
  "Arquitecto",
  "Maestro de primaria",
  "Veterinario",
  "Contador",
  "Piloto",
  "Abogado",
  "Periodista",
  "Marketing digital",
  "Psicólogo",
  "Product Manager",
  "Ingeniero civil",
  "Ingeniero mecánico",
  "Ingeniero químico",
  "Ingeniero electricista",
  "Ingeniero de telecomunicaciones",
  "Productor de musica",
  "Productor de cine",
  "Productor de televisión",
  "Científico",
  "Científico de datos",
  "Carpintero",
  "Astronauta",
  "Bibliotecario",
]